# Generated by Django 4.2.13 on 2024-06-15 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0011_alter_person_managers_person_date_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='sharedFrom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shared_from', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='person',
            name='profileId',
            field=models.CharField(default='77a06143-2329-4592-8052-164b95197a65', max_length=255),
        ),
        migrations.AlterField(
            model_name='todo',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
