# Generated by Django 4.2.13 on 2024-06-15 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0012_todo_sharedfrom_alter_person_profileid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='profileId',
            field=models.CharField(default='ed5c37cc-eec5-423c-8282-8793c5fe0f79', max_length=255),
        ),
        migrations.AlterField(
            model_name='todo',
            name='sharedFrom',
            field=models.ForeignKey(default='0333b6e3-ba41-4de4-ac36-f4e2bcc7578d', on_delete=django.db.models.deletion.CASCADE, related_name='shared_from', to=settings.AUTH_USER_MODEL),
        ),
    ]
