# Generated by Django 4.2.13 on 2024-06-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0013_alter_person_profileid_alter_todo_sharedfrom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='profileId',
            field=models.CharField(default='848e7326-148d-49bc-ac04-f56c74430d1f', max_length=255),
        ),
    ]
