# Generated by Django 4.2.13 on 2024-06-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0014_alter_person_profileid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='sharedFrom',
        ),
        migrations.AlterField(
            model_name='person',
            name='profileId',
            field=models.CharField(default='b708289d-3966-466f-aa47-f777e48108a8', max_length=255),
        ),
    ]
