# Generated by Django 4.2.13 on 2024-06-15 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0015_remove_todo_sharedfrom_alter_person_profileid'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='sharedFrom',
            field=models.ForeignKey(default='id1', on_delete=django.db.models.deletion.CASCADE, related_name='shared_from', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='person',
            name='profileId',
            field=models.CharField(default='6040a206-5414-41af-ade3-8d531d6be799', max_length=255),
        ),
    ]
