# Generated by Django 4.2.13 on 2024-06-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0016_todo_sharedfrom_alter_person_profileid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='sharedFrom',
            new_name='shared_from',
        ),
        migrations.AlterField(
            model_name='person',
            name='profileId',
            field=models.CharField(default='54189198-4e8d-46f0-a9ef-c316902d4119', max_length=255),
        ),
    ]
