# Generated by Django 4.2.13 on 2024-06-15 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0019_alter_person_profileid_alter_todo_shared_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='profileId',
            field=models.CharField(default='103bd115-7ca2-44f6-a4d6-5d383de396f6', max_length=255),
        ),
        migrations.AlterField(
            model_name='todo',
            name='shared_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_from', to=settings.AUTH_USER_MODEL),
        ),
    ]
