# Generated by Django 4.2.13 on 2024-06-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0020_alter_person_profileid_alter_todo_shared_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='profileId',
            field=models.CharField(default='5df0d841-ff44-4614-a3cb-86482da74cee', max_length=255),
        ),
    ]
